"""
FinancialDataAgent — Phase 8 Research Team.

Converts the provider company snapshot into a structured financial research
summary. Identifies what financial data is available, what is missing, and
assigns quality assessments based on source tier.

Fully deterministic — no LLM calls required.
Can optionally accept an LLM client to enrich the `financial_context_summary`
narrative, but all structural fields are computed from provider data alone.

Constraints enforced:
  - No invented numbers.
  - No valuation conclusion.
  - No investment recommendation.
  - All warnings are non-fatal — agent always returns a result.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# Source tiers considered "primary" for financial data purposes
_PRIMARY_TIERS = {"T1_primary_filing", "T2_regulator_or_gov"}
_AGGREGATOR_TIERS = {"T5_api_aggregator", "T6_model_estimate"}

# Financial data categories expected in a full company analysis
_EXPECTED_FINANCIAL_CATEGORIES = [
    "revenue",
    "ebitda",
    "ebit",
    "net_income",
    "total_assets",
    "total_debt",
    "cash_and_equivalents",
    "free_cash_flow",
    "market_cap",
    "enterprise_value",
    "ev_ebitda",
    "price_to_earnings",
    "dividend_yield",
    "earnings_per_share",
    "book_value_per_share",
    "return_on_equity",
    "debt_to_equity",
    "current_ratio",
]

# Identity / profile fields available at snapshot phase
_SNAPSHOT_FIELDS = [
    "identity.legal_name",
    "identity.ticker",
    "identity.exchange",
    "identity.country_domicile",
    "profile.sector",
    "profile.industry",
    "profile.reporting_currency",
    "profile.fiscal_year_end",
    "profile.description",
]

# Price fields available when price data exists
_PRICE_FIELDS = [
    "price_history.latest_close",
    "price_history.date_range",
    "price_history.data_points_count",
]


@dataclass
class FinancialDataAgentOutput:
    """Structured output from the FinancialDataAgent."""

    available_financial_data: list[str]
    missing_financial_data: list[str]
    data_quality_notes: list[str]
    source_tier_summary: dict  # e.g. {"T5_api_aggregator": 2, "T6_model_estimate": 0}
    financial_context_summary: str
    warnings: list[str] = field(default_factory=list)


def run_financial_data_agent(
    company_snapshot: dict,
    source_ids: list[str] | None = None,
) -> FinancialDataAgentOutput:
    """
    Analyse the company snapshot and produce a structured financial data summary.

    Args:
        company_snapshot: dict produced by build_company_snapshot().
        source_ids: list of Source record UUIDs created from provider data.

    Returns:
        FinancialDataAgentOutput — always returns, never raises.
    """
    warnings: list[str] = []
    data_quality_notes: list[str] = []

    identity = company_snapshot.get("company_identity", {})
    profile = company_snapshot.get("profile", {})
    price_summary = company_snapshot.get("price_history_summary", {})
    provider_meta = company_snapshot.get("provider_metadata", {})
    missing_fields = set(company_snapshot.get("missing_fields", []))
    is_mock = company_snapshot.get("is_mock", True)

    source_tier = provider_meta.get("source_tier", "T6_model_estimate")
    provider_name = provider_meta.get("provider_name", "unknown")

    # ── Determine available data ──────────────────────────────────────────
    available: list[str] = []
    missing: list[str] = []

    # Identity fields
    for field_path in _SNAPSHOT_FIELDS:
        section, key = field_path.split(".")
        obj = identity if section == "identity" else profile
        val = obj.get(key)
        if val is not None and field_path not in missing_fields:
            available.append(field_path)
        else:
            missing.append(field_path)

    # Price data
    if price_summary.get("available"):
        for fp in _PRICE_FIELDS:
            available.append(fp)
    else:
        for fp in _PRICE_FIELDS:
            missing.append(fp)

    # Financial fundamentals — none present at snapshot phase
    for cat in _EXPECTED_FINANCIAL_CATEGORIES:
        missing.append(f"financials.{cat}")

    # ── Source tier accounting ────────────────────────────────────────────
    source_tier_summary: dict[str, int] = {
        "T1_primary_filing": 0,
        "T2_regulator_or_gov": 0,
        "T3_industry_specialist": 0,
        "T4_quality_media": 0,
        "T5_api_aggregator": 0,
        "T6_model_estimate": 0,
    }
    if source_tier in source_tier_summary:
        source_tier_summary[source_tier] += len(source_ids) if source_ids else 1

    # ── Quality notes ─────────────────────────────────────────────────────
    if is_mock:
        data_quality_notes.append(
            "All data is MOCK — generated by MockFinancialDataProvider. "
            "Not real financial data. Not investment advice."
        )
        warnings.append(
            "Mock provider active: all values are synthetic demo data."
        )

    if source_tier in _AGGREGATOR_TIERS:
        data_quality_notes.append(
            f"Provider '{provider_name}' is classified as {source_tier}. "
            "Aggregator data should be cross-verified against primary filings (T1/T2) "
            "before use in any investment analysis."
        )
        warnings.append(
            f"Source tier {source_tier}: all identity and price data from {provider_name} "
            "is aggregator quality. Missing primary filing sources."
        )
    elif source_tier in _PRIMARY_TIERS:
        data_quality_notes.append(
            f"Provider '{provider_name}' is classified as {source_tier}. "
            "Identity data from a primary or regulatory source."
        )

    if price_summary.get("available"):
        data_quality_notes.append(
            f"Price history available: {price_summary.get('data_points_count', 0)} data points. "
            f"Latest close: {price_summary.get('latest_close', 'N/A')} "
            f"{price_summary.get('currency', '')}. "
            f"Quality: {price_summary.get('price_data_quality', 'unknown')}."
        )
    else:
        warnings.append("No price history available from provider.")

    missing_fundamentals_count = len(
        [m for m in missing if m.startswith("financials.")]
    )
    if missing_fundamentals_count > 0:
        warnings.append(
            f"{missing_fundamentals_count} financial fundamental categories missing. "
            "Filings, XBRL data or a fundamentals-capable provider required."
        )

    # ── Build summary narrative ───────────────────────────────────────────
    ticker = identity.get("ticker", "N/A")
    legal_name = identity.get("legal_name", "Unknown")
    country = identity.get("country_domicile", "unknown country")
    sector = profile.get("sector", "unknown sector")
    currency = profile.get("reporting_currency", "unknown currency")

    financial_context_summary = (
        f"{legal_name} ({ticker}) — {sector}, {country}, reporting in {currency}. "
        f"Provider: {provider_name} ({source_tier}). "
        f"Available data points: {len(available)}. "
        f"Missing data categories: {len(missing)} "
        f"(including {missing_fundamentals_count} financial fundamental fields). "
        "No financial fundamentals sourced at this phase — "
        "identity and price data only."
    )
    if is_mock:
        financial_context_summary += " [MOCK DATA — not real financial information]"

    return FinancialDataAgentOutput(
        available_financial_data=available,
        missing_financial_data=missing,
        data_quality_notes=data_quality_notes,
        source_tier_summary=source_tier_summary,
        financial_context_summary=financial_context_summary,
        warnings=warnings,
    )


def financial_data_agent_output_to_dict(output: FinancialDataAgentOutput) -> dict:
    """Serialize output to a plain dict suitable for JSON storage."""
    return {
        "available_financial_data": output.available_financial_data,
        "missing_financial_data": output.missing_financial_data,
        "data_quality_notes": output.data_quality_notes,
        "source_tier_summary": output.source_tier_summary,
        "financial_context_summary": output.financial_context_summary,
        "warnings": output.warnings,
    }
