"""Deterministic snapshot of the plans a playbook selection produces — item 20.

Used by ``test_v3_development_stage_playbook`` to prove producer / biotech / luxury plans
are byte-identical to the plans before the development-stage overlay existed. The golden
file ``fixtures/playbook_plans_before_overlay.json`` was generated by running this module
against the parent commit (``python tests/support_plan_snapshot.py <out.json>``).
"""
from __future__ import annotations

import asyncio
import json
import sys
from types import SimpleNamespace

CFG = SimpleNamespace(v3_agent_tools_enabled=True, v3_company_web_research_enabled=True, v3_web_search_enabled=True, v3_web_search_provider="fake",
                      v3_filings_tool_enabled=True, v3_corpus_enabled=True,
                      v3_commodity_sources_enabled=True)
CASES = {
    "mining_producer": dict(industry="Metals & Mining", commodities=["copper"]),
    "biotech": dict(industry="Biotechnology", commodities=[]),
    "luxury": dict(industry="Luxury Goods", commodities=[]),
    "no_playbook": dict(industry="Nothing Declared", commodities=[]),
}


def _q(q):
    c = q.evidence_contract
    return {
        "key": q.key, "text": q.text, "origin": q.origin,
        "required_tools": sorted(q.required_tools), "priority": q.priority,
        "blocking": q.blocking, "blocking_requires": q.blocking_requires,
        "required_evidence_classes": list(q.required_evidence_classes),
        "required_calculations": list(q.required_calculations), "domain": q.domain,
        "owner_role": q.owner_role, "depends_on": list(q.depends_on),
        "search_intents": list(q.search_intents), "series_labels": list(q.series_labels),
        "per_commodity": q.per_commodity, "commodity": q.commodity,
        "replaces": list(q.replaces), "optional_tools": sorted(q.optional_tools),
        "report_section": q.report_section, "contract": {
            "min_items": c.min_items, "min_distinct_sources": c.min_distinct_sources,
            "required_kinds": [[sorted(k.kinds), k.label] for k in c.required_kinds],
            "min_tier": c.min_tier, "allow_external": c.allow_external,
            "max_external_searches": c.max_external_searches},
    }


async def snapshot():
    from app.services.director.planner import plan_research
    from app.services.macro.commodities import BY_SLUG
    from app.services.pipeline.v3_pipeline import _PlaybookAdapter
    from app.services.playbooks import select

    out = {}
    for name, case in CASES.items():
        sel = select(sector=None, industry=case["industry"])
        plan = await plan_research(
            subject="ANY:US", mode="deep", playbooks=[_PlaybookAdapter(p) for p in sel.playbooks],
            cfg=CFG, commodities=[BY_SLUG[c] for c in case["commodities"]])
        out[name] = {
            "selection": sel.to_dict(),
            "plan": plan.to_dict(),
            "questions": [_q(q) for q in plan.questions],
            "tasks": [{"role": t.role_id, "questions": t.question_keys, "round": t.round_index,
                       "max_iterations": t.max_iterations, "tool_budget": t.tool_budget}
                      for t in plan.tasks],
            "unassignable": plan.unassignable,
            "degraded": plan.degraded,
        }
    return out


if __name__ == "__main__":
    import app
    print(app.__file__, file=sys.stderr)
    data = asyncio.run(snapshot())
    with open(sys.argv[1], "w") as fh:
        json.dump(data, fh, indent=1, sort_keys=True, default=str)
