"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import {
  generateFinalReportFromReport,
  regenerateFinalReportSection,
  validateFinalReport,
} from "@/lib/api";

const SECTION_OPTIONS = [
  "executive_summary",
  "company_identity",
  "discovery_rationale",
  "data_availability_summary",
  "financial_snapshot",
  "internal_scorecard",
  "valuation_readiness",
  "bull_case",
  "bear_case",
  "risk_analysis",
  "source_quality_review",
  "citation_validation_review",
  "research_completeness_review",
  "missing_information",
  "committee_chair_summary",
  "workflow_status",
  "human_review_checklist",
  "source_citation_appendix",
];

export default function FinalReportActions({ reportId }: { reportId: string }) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [sectionName, setSectionName] = useState("executive_summary");
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  function runAction(action: () => Promise<string>) {
    setError(null);
    setSuccess(null);
    startTransition(async () => {
      try {
        const message = await action();
        setSuccess(message);
        router.refresh();
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unknown error");
      }
    });
  }

  return (
    <div className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm space-y-4">
      <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">
        Final Report Actions
      </p>
      <div className="rounded border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">
        Internal admin actions only. No public publishing, no recommendations,
        and no price targets are generated by these actions.
      </div>
      <div className="flex flex-wrap gap-2">
        <button
          onClick={() =>
            runAction(async () => {
              const response = await generateFinalReportFromReport(reportId);
              return `Internal final report draft generated (report_id=${response.report_id}).`;
            })
          }
          disabled={isPending}
          className="px-3 py-1.5 text-sm font-medium rounded bg-blue-700 hover:bg-blue-800 text-white disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isPending ? "Working…" : "Generate Internal Final Report Draft"}
        </button>
        <button
          onClick={() =>
            runAction(async () => {
              const response = await validateFinalReport(reportId);
              return `Validation complete: schema_valid=${response.schema_valid}, safety_valid=${response.safety_valid}.`;
            })
          }
          disabled={isPending}
          className="px-3 py-1.5 text-sm font-medium rounded bg-purple-700 hover:bg-purple-800 text-white disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isPending ? "Working…" : "Validate Final Report"}
        </button>
      </div>
      <div className="space-y-2">
        <label className="block text-xs font-medium text-gray-700">
          Optional: Regenerate Section
        </label>
        <div className="flex flex-wrap gap-2">
          <select
            value={sectionName}
            onChange={(e) => setSectionName(e.target.value)}
            className="border border-gray-300 rounded px-2 py-1.5 text-sm"
            disabled={isPending}
          >
            {SECTION_OPTIONS.map((section) => (
              <option key={section} value={section}>
                {section}
              </option>
            ))}
          </select>
          <button
            onClick={() =>
              runAction(async () => {
                const response = await regenerateFinalReportSection(
                  reportId,
                  sectionName,
                );
                return `Section regeneration ${response.regenerated ? "completed" : "did not complete"} for ${response.section_name}.`;
              })
            }
            disabled={isPending}
            className="px-3 py-1.5 text-sm font-medium rounded bg-gray-800 hover:bg-black text-white disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isPending ? "Working…" : "Regenerate Section"}
          </button>
        </div>
      </div>
      {error && (
        <div className="rounded border border-red-200 bg-red-50 p-3 text-xs text-red-700">
          {error}
        </div>
      )}
      {success && (
        <div className="rounded border border-green-200 bg-green-50 p-3 text-xs text-green-700">
          {success}
        </div>
      )}
    </div>
  );
}
