"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import {
  generateFinalReportFromReport,
  regenerateFinalReportSection,
  validateFinalReport,
} from "@/lib/api";

const SECTION_OPTIONS = [
  "executive_summary",
  "company_identity",
  "discovery_rationale",
  "data_availability_summary",
  "financial_snapshot",
  "internal_scorecard",
  "valuation_readiness",
  "bull_case",
  "bear_case",
  "risk_analysis",
  "source_quality_review",
  "citation_validation_review",
  "research_completeness_review",
  "missing_information",
  "committee_chair_summary",
  "workflow_status",
  "human_review_checklist",
  "source_citation_appendix",
];

const selectCls =
  "rounded-lg border border-white/10 bg-white/5 px-2 py-1.5 text-sm text-slate-100 focus:border-sky-400/50 focus:outline-none focus:ring-2 focus:ring-sky-500/40";

export default function FinalReportActions({ reportId }: { reportId: string }) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [sectionName, setSectionName] = useState("executive_summary");
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  function runAction(action: () => Promise<string>) {
    setError(null);
    setSuccess(null);
    startTransition(async () => {
      try {
        const message = await action();
        setSuccess(message);
        router.refresh();
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unknown error");
      }
    });
  }

  return (
    <div className="space-y-4 rounded-2xl border border-white/10 bg-white/[0.045] p-5 shadow-[0_8px_30px_rgba(2,6,23,0.45)] backdrop-blur-xl">
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
        Final Report Actions
      </p>
      <div className="rounded-lg border border-amber-400/25 bg-amber-500/[0.09] p-3 text-xs text-amber-200">
        Internal admin actions only. No public publishing, no recommendations,
        and no price targets are generated by these actions.
      </div>
      <div className="flex flex-wrap gap-2">
        <button
          onClick={() =>
            runAction(async () => {
              const response = await generateFinalReportFromReport(reportId);
              return `Internal final report draft generated (report_id=${response.report_id}).`;
            })
          }
          disabled={isPending}
          className="rounded-lg bg-gradient-to-r from-sky-500 to-blue-600 px-3 py-1.5 text-sm font-medium text-white shadow-lg shadow-sky-500/20 transition-all hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0"
        >
          {isPending ? "Working…" : "Generate Internal Final Report Draft"}
        </button>
        <button
          onClick={() =>
            runAction(async () => {
              const response = await validateFinalReport(reportId);
              return (
                `Validation complete: schema_valid=${response.schema_valid}, ` +
                `safety_valid=${response.safety_valid}, ` +
                `research_complete=${response.research_complete}, ` +
                `publication_ready=${response.publication_ready}, ` +
                `human_review_required=${response.human_review_required}.`
              );
            })
          }
          disabled={isPending}
          className="rounded-lg bg-gradient-to-r from-violet-500 to-purple-600 px-3 py-1.5 text-sm font-medium text-white shadow-lg shadow-violet-500/20 transition-all hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0"
        >
          {isPending ? "Working…" : "Validate Final Report"}
        </button>
      </div>
      <div className="space-y-2">
        <label className="block text-xs font-medium text-slate-400">
          Optional: Regenerate Section
        </label>
        <div className="flex flex-wrap gap-2">
          <select
            value={sectionName}
            onChange={(e) => setSectionName(e.target.value)}
            className={selectCls}
            disabled={isPending}
          >
            {SECTION_OPTIONS.map((section) => (
              <option key={section} value={section} className="bg-slate-900">
                {section}
              </option>
            ))}
          </select>
          <button
            onClick={() =>
              runAction(async () => {
                const response = await regenerateFinalReportSection(
                  reportId,
                  sectionName,
                );
                return `Section regeneration ${response.regenerated ? "completed" : "did not complete"} for ${response.section_name}.`;
              })
            }
            disabled={isPending}
            className="rounded-lg border border-white/15 bg-white/5 px-3 py-1.5 text-sm font-medium text-slate-100 transition-colors hover:bg-white/10 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {isPending ? "Working…" : "Regenerate Section"}
          </button>
        </div>
      </div>
      {error && (
        <div className="rounded-lg border border-rose-400/25 bg-rose-500/[0.09] p-3 text-xs text-rose-200">
          {error}
        </div>
      )}
      {success && (
        <div className="rounded-lg border border-emerald-400/25 bg-emerald-500/[0.09] p-3 text-xs text-emerald-200">
          {success}
        </div>
      )}
    </div>
  );
}
