import Link from "next/link";
import { notFound } from "next/navigation";
import { fetchReport } from "@/lib/api";
import type { Report } from "@/types/api";

function Badge({
  label,
  color,
}: {
  label: string;
  color: "gray" | "amber" | "green" | "red" | "blue" | "purple";
}) {
  const styles: Record<string, string> = {
    gray: "bg-gray-100 text-gray-700",
    amber: "bg-amber-100 text-amber-800",
    green: "bg-green-100 text-green-800",
    red: "bg-red-100 text-red-800",
    blue: "bg-blue-100 text-blue-800",
    purple: "bg-purple-100 text-purple-800",
  };
  return (
    <span
      className={`inline-block px-2 py-0.5 rounded text-xs font-semibold ${styles[color]}`}
    >
      {label}
    </span>
  );
}

function MetaRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex gap-2 text-sm">
      <span className="text-gray-500 w-40 shrink-0">{label}</span>
      <span className="text-gray-800 font-mono text-xs">{value}</span>
    </div>
  );
}

async function getReport(id: string): Promise<Report | null> {
  try {
    return await fetchReport(id);
  } catch {
    return null;
  }
}

export default async function ReportDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const report = await getReport(id);

  if (!report) {
    notFound();
  }

  return (
    <div className="max-w-3xl space-y-6">
      {/* Back */}
      <Link
        href="/admin/reports"
        className="text-sm text-gray-400 hover:text-gray-700"
      >
        ← All Reports
      </Link>

      {/* Header badges */}
      <div className="flex flex-wrap gap-2">
        <Badge label="Admin Draft Only" color="red" />
        <Badge label="Not Investment Advice" color="red" />
        <Badge label="Not a Public Recommendation" color="red" />
        <Badge label="Human Review Required" color="amber" />
        <Badge label={report.status} color="amber" />
        <Badge label={report.report_type} color="gray" />
      </div>

      {/* Disclaimer */}
      <div className="rounded-lg border border-red-200 bg-red-50 p-4">
        <p className="text-sm font-semibold text-red-800 mb-1">
          Internal Admin Draft — Not Investment Advice
        </p>
        <ul className="text-xs text-red-700 space-y-0.5 list-disc list-inside">
          <li>
            This is an internal draft generated by the AI research workflow.
          </li>
          <li>It has not been reviewed or approved for publication.</li>
          <li>
            It does not constitute investment advice, a recommendation, or a
            solicitation.
          </li>
          <li>No BUY / SELL / HOLD / WATCH recommendation is contained here.</li>
          <li>
            Internal workflow statuses (e.g.{" "}
            <code className="font-mono">research_incomplete</code>) are
            operational metadata — not public-facing ratings.
          </li>
        </ul>
      </div>

      {/* Title */}
      <div>
        <h1 className="text-2xl font-bold text-gray-900">{report.title}</h1>
        {report.summary && (
          <p className="text-sm text-gray-600 mt-2">{report.summary}</p>
        )}
      </div>

      {/* Metadata */}
      <div className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm space-y-2">
        <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">
          Metadata
        </p>
        <MetaRow label="Report ID" value={report.id} />
        <MetaRow label="Type" value={report.report_type} />
        <MetaRow label="Status" value={report.status} />
        {report.created_by_agent_run_id && (
          <MetaRow
            label="Agent Run ID"
            value={report.created_by_agent_run_id}
          />
        )}
        <MetaRow
          label="Created"
          value={new Date(report.created_at).toLocaleString()}
        />
        <MetaRow
          label="Updated"
          value={new Date(report.updated_at).toLocaleString()}
        />
        {report.published_at && (
          <MetaRow
            label="Published at"
            value={new Date(report.published_at).toLocaleString()}
          />
        )}
        {report.period_start && (
          <MetaRow label="Period start" value={report.period_start} />
        )}
        {report.period_end && (
          <MetaRow label="Period end" value={report.period_end} />
        )}
      </div>

      {/* Markdown content */}
      {report.content_markdown ? (
        <div className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm">
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">
            Report Content (Markdown)
          </p>
          <div className="text-xs text-gray-400 mb-3 italic">
            Raw markdown — content is an unformatted admin draft produced by AI
            agents. Not validated for accuracy. Not investment advice.
          </div>
          <pre className="whitespace-pre-wrap text-xs text-gray-800 font-mono bg-gray-50 rounded p-4 overflow-auto max-h-[600px] border border-gray-100">
            {report.content_markdown}
          </pre>
        </div>
      ) : (
        <div className="rounded-lg border border-gray-100 bg-gray-50 p-5 text-center text-gray-400 text-sm">
          No content markdown available for this report.
        </div>
      )}

      {/* Actions placeholder */}
      <div className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm">
        <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">
          Actions
        </p>
        <div className="flex gap-3">
          <button
            disabled
            className="px-3 py-1.5 text-sm rounded border border-gray-300 text-gray-400 cursor-not-allowed"
            title="Publish — not yet implemented"
          >
            Publish (Phase 11)
          </button>
          <button
            disabled
            className="px-3 py-1.5 text-sm rounded border border-gray-300 text-gray-400 cursor-not-allowed"
            title="Reject — not yet implemented"
          >
            Reject (Phase 11)
          </button>
        </div>
        <p className="text-xs text-gray-400 mt-2">
          Publish and Reject actions will be implemented in Phase 11 with
          explicit human-admin controls and audit logging.
        </p>
      </div>
    </div>
  );
}
