"""
MockFinancialDataProvider — deterministic synthetic data for tests and CI.

Rules:
- No network calls. Ever.
- All returned data is clearly marked is_mock=True.
- Values are plausible in shape but MUST NOT be used as real investment data.
- The fictional company used is "Acme Nordic AS" (ticker "ACME", exchange "OSE").
  It does not exist and the data is purely structural demo data.
- Any ticker is accepted; the same deterministic data is returned for all.
"""

from __future__ import annotations

from datetime import datetime, timezone

from app.integrations.financial_data_provider import (
    CompanyProfileData,
    DataQuality,
    FinancialDataProvider,
    FundamentalDataPoint,
    FundamentalsData,
    PriceHistoryData,
    PricePoint,
    ProviderCapability,
    ProviderResponseMetadata,
    ProviderStatus,
    SourceTier,
)

_MOCK_NOTE = (
    "DEMO DATA — generated by MockFinancialDataProvider. "
    "Not real financial data. Not investment advice."
)

_FIXED_PRICE_SERIES = [
    ("2026-01-02", 10.00, 10.50, 9.80, 10.20, 123000),
    ("2026-01-03", 10.20, 10.70, 10.10, 10.55, 98000),
    ("2026-01-06", 10.55, 11.00, 10.40, 10.90, 145000),
    ("2026-01-07", 10.90, 11.20, 10.75, 11.05, 112000),
    ("2026-01-08", 11.05, 11.30, 10.95, 11.15, 87000),
]


class MockFinancialDataProvider(FinancialDataProvider):
    """Returns deterministic demo data. Used in all CI tests."""

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def source_tier(self) -> SourceTier:
        return SourceTier.T6_model_estimate

    def get_supported_capabilities(self) -> list[ProviderCapability]:
        return [
            ProviderCapability.company_profile,
            ProviderCapability.price_history,
            ProviderCapability.fundamentals,
        ]

    def get_provider_status(self) -> ProviderStatus:
        return ProviderStatus.ok

    def _meta(self) -> ProviderResponseMetadata:
        return ProviderResponseMetadata(
            provider_name=self.provider_name,
            source_tier=self.source_tier,
            retrieved_at=datetime(2026, 6, 20, 12, 0, 0, tzinfo=timezone.utc),
            is_mock=True,
            status=ProviderStatus.ok,
            note=_MOCK_NOTE,
        )

    async def get_company_profile(
        self,
        ticker: str,
        exchange: str | None = None,
    ) -> CompanyProfileData:
        return CompanyProfileData(
            ticker=ticker,
            exchange=exchange or "OSE",
            legal_name="Acme Nordic AS [MOCK]",
            country_domicile="Norway",
            reporting_currency="NOK",
            fiscal_year_end="December",
            sector="Industrials",
            industry="Electrical Equipment",
            description=(
                "[MOCK DATA] Acme Nordic AS is a fictional company used for "
                "provider smoke tests. It does not exist and this data is not "
                "investment advice."
            ),
            website=None,
            isin=None,
            lei=None,
            ipo_date="2020-01-15",
            source_url=None,
            data_quality=DataQuality.D_weak_or_stale,
            meta=self._meta(),
        )

    async def get_price_history(
        self,
        ticker: str,
        exchange: str | None = None,
        start_date: str | None = None,
        end_date: str | None = None,
    ) -> PriceHistoryData:
        price_points = [
            PricePoint(
                date=date,
                open=open_,
                high=high,
                low=low,
                close=close,
                volume=volume,
                adjusted_close=close,
            )
            for date, open_, high, low, close, volume in _FIXED_PRICE_SERIES
        ]
        return PriceHistoryData(
            ticker=ticker,
            exchange=exchange or "OSE",
            currency="NOK",
            price_points=price_points,
            source_url=None,
            data_quality=DataQuality.D_weak_or_stale,
            meta=self._meta(),
        )

    async def get_fundamentals(
        self,
        ticker: str,
        exchange: str | None = None,
    ) -> FundamentalsData:
        datapoints = [
            FundamentalDataPoint(
                field_name="market_cap_usd_m",
                value=120.0,
                unit="USD_m",
                as_of="2026-06-20",
                currency="USD",
                source_tier=SourceTier.T6_model_estimate,
                source_name="MockFinancialDataProvider",
                source_url=None,
                data_quality=DataQuality.D_weak_or_stale,
                note="[MOCK] Fictional value. Not real financial data.",
            ),
            FundamentalDataPoint(
                field_name="revenue_ttm_usd_m",
                value=85.0,
                unit="USD_m",
                as_of="2026-06-20",
                currency="USD",
                source_tier=SourceTier.T6_model_estimate,
                source_name="MockFinancialDataProvider",
                source_url=None,
                data_quality=DataQuality.D_weak_or_stale,
                note="[MOCK] Fictional value. Not real financial data.",
            ),
            FundamentalDataPoint(
                field_name="ebitda_ttm_usd_m",
                value=18.5,
                unit="USD_m",
                as_of="2026-06-20",
                currency="USD",
                source_tier=SourceTier.T6_model_estimate,
                source_name="MockFinancialDataProvider",
                source_url=None,
                data_quality=DataQuality.D_weak_or_stale,
                note="[MOCK] Fictional value. Not real financial data.",
            ),
        ]
        return FundamentalsData(
            ticker=ticker,
            exchange=exchange or "OSE",
            datapoints=datapoints,
            meta=self._meta(),
        )
