"""
Phase 16: Final Report Generator Service.

Generates structured internal final report drafts for scored candidates and
analyzed companies. Combines discovery result, scorecard, company snapshot,
financial data, Research Team outputs, Analysis Council outputs, citations,
source-quality checks, and human-review workflow into a single structured report.

IMPORTANT CONSTRAINTS:
  - No BUY/SELL/HOLD/WATCH public recommendations are produced.
  - No price targets, fair values, or upside percentages are produced.
  - No personalized investment advice is produced.
  - No public publishing — all reports are saved as admin-only drafts.
  - Human review is always required (human_review_required=True).
  - Safety gate blocks any forbidden language from entering final reports.
  - Schema validation runs but failure does NOT block draft creation;
    schema_valid=False is stored with validation errors for human review.
  - LLM is optional and off by default (fully testable offline).

Every sourced fact is labelled with its provenance type:
  sourced_fact        — from DB record or provider with cited source
  model_interpretation — generated by deterministic logic / LLM
  missing_data        — field not available
  assumption          — inferred without a primary source
  human_review_required — must be checked by admin before approval
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.report import Report
from app.models.scorecard import Scorecard
from app.models.screening import ScreeningCandidate
from app.models.source import Citation, Source
from app.schemas.final_report import (
    FINAL_REPORT_VERSION,
    INTERNAL_DISCLAIMER,
    FinalReportResponse,
    FinalReportValidateResponse,
    HumanReviewChecklistItem,
    RegenerateSectionResponse,
    SafetyValidationResult,
)
from app.services.report_validation_service import validate_real_asset_report

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Safety gate — forbidden output terms
# ---------------------------------------------------------------------------

_FORBIDDEN_TERMS: list[str] = [
    "BUY",
    "SELL",
    "HOLD",
    "WATCH",
    "price target",
    "target price",
    "fair value",
    "intrinsic value",
    "upside of",
    "upside percentage",
    "upside%",
    "guaranteed return",
    "will go up",
    "will go down",
    "personalized advice",
    "tailored recommendation",
    "shortlist_high",
    "SHORTLIST_HIGH",
]

# Allowed internal status labels (research queue — never public recommendations)
ALLOWED_INTERNAL_STATUSES = {
    "not_enough_data",
    "low_priority_research",
    "needs_primary_sources",
    "ready_for_deeper_analysis",
    "high_priority_for_human_review",
    "reject_due_to_data_quality",
}

# Sections that are always required in a final report
_REQUIRED_SECTIONS = [
    "admin_disclaimer",
    "executive_summary",
    "company_identity",
    "discovery_rationale",
    "data_availability_summary",
    "financial_snapshot",
    "internal_scorecard",
    "valuation_readiness",
    "bull_case",
    "bear_case",
    "risk_analysis",
    "source_quality_review",
    "citation_validation_review",
    "research_completeness_review",
    "missing_information",
    "committee_chair_summary",
    "workflow_status",
    "human_review_checklist",
    "source_citation_appendix",
]


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# Safety gate
# ---------------------------------------------------------------------------


def run_safety_gate(report_content: dict[str, Any]) -> SafetyValidationResult:
    """
    Scan all text in the report for forbidden output terms.

    Forbidden terms include: BUY, SELL, HOLD, WATCH, price target, fair value,
    upside percentage, guaranteed return, personalized advice, etc.

    Returns a SafetyValidationResult. If any forbidden term is found:
      - passed=False
      - blocks_approval=True
      - report must be saved as draft only
      - human revision is required before approval

    Note: certain field names are exempt from scanning because they exist to
    explicitly enumerate what is NOT produced (e.g. disallowed_outputs from the
    valuation guard agent). Scanning these would generate false positives.
    """
    found_terms: list[str] = []
    scanned_sections: list[str] = []
    warnings: list[str] = []

    # Fields that enumerate what is NOT allowed — exempt from scanning
    _EXEMPT_FIELD_NAMES = frozenset(
        {
            "disallowed_outputs",
            "blocked_methods",
            "forbidden_terms_found",
            "forbidden_terms",
            "prohibited_outputs",
        }
    )

    def _scan_value(val: Any, path: str) -> None:
        # Skip if the leaf key is an exempt field
        leaf_key = path.rsplit(".", 1)[-1].split("[")[0]
        if leaf_key in _EXEMPT_FIELD_NAMES:
            return
        if isinstance(val, str):
            upper = val.upper()
            for term in _FORBIDDEN_TERMS:
                if term.upper() in upper:
                    found_terms.append(f"'{term}' in {path}")
        elif isinstance(val, dict):
            for k, v in val.items():
                if k not in _EXEMPT_FIELD_NAMES:
                    _scan_value(v, f"{path}.{k}")
        elif isinstance(val, list):
            for i, item in enumerate(val):
                _scan_value(item, f"{path}[{i}]")

    for section_name, section_content in report_content.items():
        scanned_sections.append(section_name)
        _scan_value(section_content, section_name)

    passed = len(found_terms) == 0
    if not passed:
        warnings.append(
            "SAFETY GATE FAILURE: Forbidden output terms detected. "
            "Report saved as draft only. Human revision required before approval."
        )

    return SafetyValidationResult(
        passed=passed,
        forbidden_terms_found=found_terms,
        scanned_sections=scanned_sections,
        warnings=warnings,
        blocks_approval=not passed,
    )


# ---------------------------------------------------------------------------
# Section builders (deterministic — no LLM required)
# ---------------------------------------------------------------------------


def _build_admin_disclaimer() -> dict[str, Any]:
    return {
        "type": "admin_disclaimer",
        "content": INTERNAL_DISCLAIMER,
        "classification": "admin_only",
        "provenance": "static_system_text",
        "human_review_required": False,
    }


def _build_executive_summary(
    company_name: str | None,
    ticker: str | None,
    scorecard: Scorecard | None,
    committee_chair_summary: dict[str, Any] | None,
    provisional_internal_status: str | None,
) -> dict[str, Any]:
    status = provisional_internal_status or "not_enough_data"
    if status not in ALLOWED_INTERNAL_STATUSES:
        status = "not_enough_data"

    overall_score = None
    score_note = "Scorecard not available."
    if scorecard:
        overall_score = scorecard.overall_score
        score_note = (
            f"Research attractiveness score: {overall_score}/100 "
            f"(internal queue label: {scorecard.internal_status}). "
            "Score is NOT a public recommendation."
        )

    committee_note = "Analysis council summary not available."
    if committee_chair_summary:
        committee_note = committee_chair_summary.get(
            "committee_summary", "Analysis council summary not available."
        )

    return {
        "type": "executive_summary",
        "company_name": company_name or "Unknown",
        "ticker": ticker,
        "overall_score": overall_score,
        "internal_status": status,
        "score_note": {
            "value": score_note,
            "provenance": "sourced_fact" if scorecard else "missing_data",
            "human_review_required": True,
        },
        "committee_note": {
            "value": committee_note,
            "provenance": "model_interpretation",
            "human_review_required": True,
        },
        "disclaimer": "INTERNAL ADMIN DRAFT. NOT INVESTMENT ADVICE. Human review required.",
        "human_review_required": True,
    }


def _build_company_identity(
    company_snapshot: dict[str, Any] | None,
    company_record: dict[str, Any] | None,
) -> dict[str, Any]:
    identity: dict[str, Any] = {"type": "company_identity"}

    def _dp(value: Any, source: str, provenance: str = "sourced_fact") -> dict:
        return {
            "value": value,
            "source": source,
            "provenance": provenance,
            "human_review_required": value is None,
        }

    if company_snapshot:
        ci = company_snapshot.get("company_identity", {})
        profile = company_snapshot.get("profile", {})
        identity["legal_name"] = _dp(ci.get("legal_name"), "company_snapshot")
        identity["ticker"] = _dp(ci.get("ticker"), "company_snapshot")
        identity["exchange"] = _dp(ci.get("exchange"), "company_snapshot")
        identity["country_domicile"] = _dp(
            ci.get("country_domicile"), "company_snapshot"
        )
        identity["isin"] = _dp(
            ci.get("isin"),
            "company_snapshot",
            "missing_data" if not ci.get("isin") else "sourced_fact",
        )
        identity["lei"] = _dp(
            ci.get("lei"),
            "company_snapshot",
            "missing_data" if not ci.get("lei") else "sourced_fact",
        )
        identity["sector"] = _dp(
            profile.get("sector"), "company_snapshot.profile"
        )
        identity["reporting_currency"] = _dp(
            profile.get("reporting_currency"), "company_snapshot.profile"
        )
        identity["source_tier"] = company_snapshot.get(
            "source_tier", "T6_model_estimate"
        )
        identity["is_mock"] = company_snapshot.get("is_mock", True)
    elif company_record:
        identity["legal_name"] = _dp(company_record.get("name"), "company_db_record")
        identity["ticker"] = _dp(company_record.get("ticker"), "company_db_record")
        identity["exchange"] = _dp(company_record.get("exchange"), "company_db_record")
        identity["country_domicile"] = _dp(
            company_record.get("country"), "company_db_record"
        )
        identity["sector"] = _dp(
            company_record.get("sector"), "company_db_record"
        )
        identity["source_tier"] = "T6_model_estimate"
        identity["is_mock"] = True
    else:
        identity["legal_name"] = _dp(None, "unavailable", "missing_data")
        identity["source_tier"] = "T6_model_estimate"
        identity["is_mock"] = True

    identity["human_review_required"] = True
    return identity


def _build_discovery_rationale(candidate: ScreeningCandidate | None) -> dict[str, Any]:
    if candidate is None:
        return {
            "type": "discovery_rationale",
            "available": False,
            "note": {
                "value": "No screening candidate linked to this report.",
                "provenance": "missing_data",
            },
            "human_review_required": True,
        }

    reasons = candidate.discovery_reasons_json or []
    available_data = candidate.available_data_json or []
    missing_data = candidate.missing_data_json or []
    warnings = candidate.warnings_json or []

    return {
        "type": "discovery_rationale",
        "available": True,
        "candidate_id": str(candidate.id),
        "ticker": candidate.ticker,
        "exchange": candidate.exchange,
        "candidate_status": candidate.candidate_status,
        "source_tier": candidate.source_tier or "T6_model_estimate",
        "data_quality": candidate.data_quality or "D_weak_or_stale",
        "discovery_reasons": {
            "value": reasons,
            "provenance": "sourced_fact",
            "human_review_required": False,
        },
        "available_data_at_discovery": {
            "value": available_data,
            "provenance": "sourced_fact",
        },
        "missing_data_at_discovery": {
            "value": missing_data,
            "provenance": "sourced_fact",
        },
        "warnings": warnings,
        "human_review_required": True,
    }


def _build_data_availability_summary(
    financial_data_summary: dict[str, Any] | None,
    fundamentals_available: bool | None,
    source_tier: str | None,
) -> dict[str, Any]:
    tier = source_tier or "T6_model_estimate"
    is_mock = tier == "T6_model_estimate"

    if financial_data_summary:
        return {
            "type": "data_availability_summary",
            "source_tier": tier,
            "is_mock": is_mock,
            "fundamentals_available": fundamentals_available or False,
            "available_count": financial_data_summary.get("available_count", 0),
            "missing_count": financial_data_summary.get("missing_count", 0),
            "warnings_count": financial_data_summary.get("warnings_count", 0),
            "available_fields": {
                "value": financial_data_summary.get("available_fields", []),
                "provenance": "sourced_fact",
            },
            "missing_fields": {
                "value": financial_data_summary.get("missing_fields", []),
                "provenance": "sourced_fact",
            },
            "warnings": financial_data_summary.get("warnings", []),
            "human_review_required": is_mock or not fundamentals_available,
        }

    return {
        "type": "data_availability_summary",
        "source_tier": tier,
        "is_mock": is_mock,
        "fundamentals_available": fundamentals_available or False,
        "available_count": 0,
        "missing_count": 0,
        "note": {
            "value": "Financial data summary not available from analysis workflow.",
            "provenance": "missing_data",
        },
        "human_review_required": True,
    }


def _build_financial_snapshot(
    company_snapshot: dict[str, Any] | None,
    fundamentals_data: dict[str, Any] | None,
) -> dict[str, Any]:
    section: dict[str, Any] = {
        "type": "financial_snapshot",
        "human_review_required": True,
    }

    if company_snapshot:
        section["source_tier"] = company_snapshot.get("source_tier", "T6_model_estimate")
        section["is_mock"] = company_snapshot.get("is_mock", True)
        section["retrieved_at"] = company_snapshot.get("retrieved_at")

        price_history = company_snapshot.get("price_history_summary", {})
        if price_history.get("available"):
            section["latest_close"] = {
                "value": price_history.get("latest_close"),
                "currency": price_history.get("currency"),
                "as_of": price_history.get("date_range", {}).get("end"),
                "provenance": "sourced_fact",
                "source": "provider_price_history",
            }
        else:
            section["latest_close"] = {
                "value": None,
                "provenance": "missing_data",
            }

        if fundamentals_data:
            highlights = fundamentals_data.get("highlights", {})

            def _fund_dp(key: str, unit: str | None = None) -> dict:
                val = highlights.get(key)
                return {
                    "value": val,
                    "unit": unit,
                    "provenance": "sourced_fact" if val is not None else "missing_data",
                    "source_tier": "T5_api_aggregator",
                    "source": "eodhd_fundamentals",
                    "human_review_required": val is None,
                }

            section["market_cap_usd_m"] = _fund_dp("market_capitalization", "USD_m")
            section["ebitda_ttm_usd_m"] = _fund_dp("ebitda", "USD_m")
            section["revenue_ttm_usd_m"] = _fund_dp("revenue_ttm", "USD_m")
            section["pe_ratio"] = _fund_dp("pe_ratio")
            section["fundamentals_note"] = {
                "value": (
                    "Fundamentals from EODHD (T5 aggregator). "
                    "Must be validated against T1 filings before use."
                ),
                "provenance": "assumption",
            }
        else:
            section["fundamentals_note"] = {
                "value": "Fundamentals not available. Run with EODHD provider or add T1 filings.",
                "provenance": "missing_data",
            }
    else:
        section["note"] = {
            "value": "Company snapshot not available. Run company analysis workflow first.",
            "provenance": "missing_data",
        }
        section["source_tier"] = "T6_model_estimate"
        section["is_mock"] = True

    return section


def _build_internal_scorecard(scorecard: Scorecard | None) -> dict[str, Any]:
    if scorecard is None:
        return {
            "type": "internal_scorecard",
            "available": False,
            "note": {
                "value": "No scorecard linked. Run scoring workflow first.",
                "provenance": "missing_data",
            },
            "human_review_required": True,
        }

    scores = scorecard.scores_json or {}
    return {
        "type": "internal_scorecard",
        "available": True,
        "scorecard_id": str(scorecard.id),
        "overall_score": {
            "value": scorecard.overall_score,
            "unit": "0_to_100",
            "provenance": "sourced_fact",
            "source": "scoring_engine_phase15",
        },
        "internal_status": {
            "value": scorecard.internal_status,
            "provenance": "sourced_fact",
            "note": "Research queue label only — not a public investment recommendation.",
        },
        "score_type": scorecard.score_type,
        "dimension_scores": {
            "value": scores,
            "provenance": "sourced_fact",
        },
        "warnings": {
            "value": scorecard.warnings_json or [],
            "provenance": "sourced_fact",
        },
        "missing_data": {
            "value": scorecard.missing_data_json or [],
            "provenance": "sourced_fact",
        },
        "source_quality_summary": {
            "value": scorecard.source_quality_summary_json or {},
            "provenance": "sourced_fact",
        },
        "disclaimer": (
            "INTERNAL SCORE ONLY. Not investment advice. "
            "Not a public trading recommendation."
        ),
        "human_review_required": True,
    }


def _build_valuation_readiness(
    valuation_guard_summary: dict[str, Any] | None,
    scorecard: Scorecard | None,
) -> dict[str, Any]:
    section: dict[str, Any] = {
        "type": "valuation_readiness",
        "disclaimer": (
            "Valuation readiness check only. "
            "No valuation estimates or return projections are produced here."
        ),
        "human_review_required": True,
    }

    if valuation_guard_summary:
        section["readiness"] = {
            "value": valuation_guard_summary.get("valuation_readiness", "not_ready"),
            "provenance": "sourced_fact",
            "source": "valuation_guard_agent_phase9",
        }
        section["available_inputs"] = {
            "value": valuation_guard_summary.get("available_valuation_inputs", []),
            "provenance": "sourced_fact",
        }
        section["missing_inputs"] = {
            "value": valuation_guard_summary.get("missing_valuation_inputs", []),
            "provenance": "sourced_fact",
        }
        section["blockers"] = {
            "value": valuation_guard_summary.get("valuation_blockers", []),
            "provenance": "sourced_fact",
        }
        section["allowed_next_steps"] = {
            "value": valuation_guard_summary.get("allowed_next_steps", []),
            "provenance": "sourced_fact",
        }
        section["disallowed_outputs"] = {
            "value": valuation_guard_summary.get(
                "disallowed_outputs",
                ["price target", "fair value", "upside percentage"],
            ),
            "provenance": "sourced_fact",
        }
        section["warnings"] = valuation_guard_summary.get("warnings", [])
    elif scorecard:
        scores = scorecard.scores_json or {}
        vr_score = scores.get("valuation_readiness_score", {})
        section["readiness"] = {
            "value": "not_ready",
            "note": "Derived from scorecard; confirm with valuation guard agent.",
            "provenance": "assumption",
        }
        section["valuation_readiness_score"] = {
            "value": vr_score.get("score", 0),
            "provenance": "sourced_fact",
        }
    else:
        section["readiness"] = {
            "value": "not_ready",
            "note": "Valuation guard summary not available.",
            "provenance": "missing_data",
        }

    return section


def _build_bull_case(bull_case_summary: dict[str, Any] | None) -> dict[str, Any]:
    if bull_case_summary is None:
        return {
            "type": "bull_case",
            "available": False,
            "note": {
                "value": "Bull case summary not available. Run company analysis workflow.",
                "provenance": "missing_data",
            },
            "human_review_required": True,
        }

    return {
        "type": "bull_case",
        "available": True,
        "positive_thesis_points": {
            "value": bull_case_summary.get("positive_thesis_points", []),
            "provenance": "model_interpretation",
            "source": "bull_case_agent_phase9",
        },
        "potential_tailwinds": {
            "value": bull_case_summary.get("potential_tailwinds", []),
            "provenance": "model_interpretation",
        },
        "evidence_used": {
            "value": bull_case_summary.get("evidence_used", []),
            "provenance": "sourced_fact",
        },
        "assumptions": {
            "value": bull_case_summary.get("assumptions", []),
            "provenance": "assumption",
        },
        "missing_evidence": {
            "value": bull_case_summary.get("missing_evidence", []),
            "provenance": "missing_data",
        },
        "confidence_level": {
            "value": bull_case_summary.get("confidence_level", "low"),
            "provenance": "model_interpretation",
        },
        "warnings": bull_case_summary.get("warnings", []),
        "human_review_required": True,
    }


def _build_bear_case(bear_case_summary: dict[str, Any] | None) -> dict[str, Any]:
    if bear_case_summary is None:
        return {
            "type": "bear_case",
            "available": False,
            "note": {
                "value": "Bear case summary not available. Run company analysis workflow.",
                "provenance": "missing_data",
            },
            "human_review_required": True,
        }

    return {
        "type": "bear_case",
        "available": True,
        "negative_thesis_points": {
            "value": bear_case_summary.get("negative_thesis_points", []),
            "provenance": "model_interpretation",
            "source": "bear_case_agent_phase9",
        },
        "potential_headwinds": {
            "value": bear_case_summary.get("potential_headwinds", []),
            "provenance": "model_interpretation",
        },
        "key_unknowns": {
            "value": bear_case_summary.get("key_unknowns", []),
            "provenance": "missing_data",
        },
        "evidence_used": {
            "value": bear_case_summary.get("evidence_used", []),
            "provenance": "sourced_fact",
        },
        "missing_evidence": {
            "value": bear_case_summary.get("missing_evidence", []),
            "provenance": "missing_data",
        },
        "confidence_level": {
            "value": bear_case_summary.get("confidence_level", "low"),
            "provenance": "model_interpretation",
        },
        "warnings": bear_case_summary.get("warnings", []),
        "human_review_required": True,
    }


def _build_risk_analysis(risk_summary: dict[str, Any] | None) -> dict[str, Any]:
    if risk_summary is None:
        return {
            "type": "risk_analysis",
            "available": False,
            "note": {
                "value": "Risk summary not available. Run company analysis workflow.",
                "provenance": "missing_data",
            },
            "human_review_required": True,
        }

    return {
        "type": "risk_analysis",
        "available": True,
        "business_risks": {
            "value": risk_summary.get("business_risks", []),
            "provenance": "model_interpretation",
            "source": "risk_agent_phase9",
        },
        "financial_risks": {
            "value": risk_summary.get("financial_risks", []),
            "provenance": "model_interpretation",
        },
        "market_risks": {
            "value": risk_summary.get("market_risks", []),
            "provenance": "model_interpretation",
        },
        "regulatory_geopolitical_risks": {
            "value": risk_summary.get("regulatory_geopolitical_risks", []),
            "provenance": "model_interpretation",
        },
        "data_quality_risks": {
            "value": risk_summary.get("data_quality_risks", []),
            "provenance": "sourced_fact",
        },
        "source_quality_risks": {
            "value": risk_summary.get("source_quality_risks", []),
            "provenance": "sourced_fact",
        },
        "risk_summary_text": {
            "value": risk_summary.get("risk_summary", ""),
            "provenance": "model_interpretation",
        },
        "warnings": risk_summary.get("warnings", []),
        "human_review_required": True,
    }


def _build_source_quality_review(
    source_quality_summary: dict[str, Any] | None,
    sources: list[Source],
) -> dict[str, Any]:
    section: dict[str, Any] = {
        "type": "source_quality_review",
        "total_sources": len(sources),
        "human_review_required": True,
    }

    if source_quality_summary:
        section["overall_source_quality"] = {
            "value": source_quality_summary.get("overall_source_quality", "unknown"),
            "provenance": "sourced_fact",
            "source": "source_quality_agent_phase8",
        }
        section["weak_sources_count"] = source_quality_summary.get(
            "weak_sources_count", 0
        )
        section["strong_sources_count"] = source_quality_summary.get(
            "strong_sources_count", 0
        )
        section["t5_promoted_warnings"] = {
            "value": source_quality_summary.get("t5_promoted_warnings", []),
            "provenance": "sourced_fact",
        }
        section["warnings"] = source_quality_summary.get("warnings", [])
    else:
        section["note"] = {
            "value": "Source quality agent summary not available. Run company analysis workflow.",
            "provenance": "missing_data",
        }

    # Summarise DB sources
    if sources:
        tier_counts: dict[str, int] = {}
        source_list = []
        for s in sources:
            source_list.append(
                {
                    "id": str(s.id),
                    "source_type": s.source_type,
                    "title": s.title,
                    "url": s.url,
                    "publisher": s.publisher,
                    "credibility_score": (
                        float(s.credibility_score) if s.credibility_score else None
                    ),
                    "retrieved_at": (
                        s.retrieved_at.isoformat() if s.retrieved_at else None
                    ),
                    "provenance": "sourced_fact",
                }
            )
            tier_counts[s.source_type] = tier_counts.get(s.source_type, 0) + 1
        section["source_type_distribution"] = {
            "value": tier_counts,
            "provenance": "sourced_fact",
        }
        section["source_list"] = source_list
    else:
        section["source_list"] = []
        section["note_no_sources"] = {
            "value": "No sources found in DB for this report.",
            "provenance": "missing_data",
        }

    return section


def _build_citation_validation_review(
    upgraded_citation_validation: dict[str, Any] | None,
    citations: list[Citation],
) -> dict[str, Any]:
    section: dict[str, Any] = {
        "type": "citation_validation_review",
        "total_citations": len(citations),
        "human_review_required": True,
    }

    if upgraded_citation_validation:
        section["status"] = {
            "value": upgraded_citation_validation.get("status", "unknown"),
            "provenance": "sourced_fact",
            "source": "citation_validator_v2_phase8",
        }
        section["bare_numbers_found"] = upgraded_citation_validation.get(
            "bare_numbers_found", []
        )
        section["weak_citation_warnings"] = upgraded_citation_validation.get(
            "weak_citation_warnings", []
        )
        section["approved_fields"] = {
            "value": upgraded_citation_validation.get("approved_fields", []),
            "provenance": "sourced_fact",
        }
        section["warnings"] = upgraded_citation_validation.get("warnings", [])
    else:
        section["note"] = {
            "value": "Citation validation summary not available. Run company analysis workflow.",
            "provenance": "missing_data",
        }

    return section


def _build_research_completeness_review(
    research_completeness_summary: dict[str, Any] | None,
) -> dict[str, Any]:
    if research_completeness_summary is None:
        return {
            "type": "research_completeness_review",
            "available": False,
            "note": {
                "value": "Research completeness summary not available.",
                "provenance": "missing_data",
            },
            "human_review_required": True,
        }

    return {
        "type": "research_completeness_review",
        "available": True,
        "complete_sections": {
            "value": research_completeness_summary.get("complete_sections", []),
            "provenance": "sourced_fact",
            "source": "research_completeness_agent_phase8",
        },
        "incomplete_sections": {
            "value": research_completeness_summary.get("incomplete_sections", []),
            "provenance": "sourced_fact",
        },
        "blocking_gaps_count": research_completeness_summary.get(
            "blocking_gaps_count", 0
        ),
        "non_blocking_gaps_count": research_completeness_summary.get(
            "non_blocking_gaps_count", 0
        ),
        "next_research_tasks": {
            "value": research_completeness_summary.get("next_research_tasks", []),
            "provenance": "model_interpretation",
        },
        "warnings": research_completeness_summary.get("warnings", []),
        "human_review_required": True,
    }


def _build_missing_information(
    financial_data_summary: dict[str, Any] | None,
    research_completeness_summary: dict[str, Any] | None,
    company_snapshot: dict[str, Any] | None,
    candidate: ScreeningCandidate | None,
) -> dict[str, Any]:
    missing: list[dict[str, str]] = []

    # From snapshot missing fields
    if company_snapshot:
        for field in company_snapshot.get("missing_fields", []):
            missing.append({"field": field, "source": "company_snapshot"})

    # From financial data
    if financial_data_summary:
        for field in financial_data_summary.get("missing_fields", []):
            if field not in [m["field"] for m in missing]:
                missing.append({"field": field, "source": "financial_data_agent"})

    # From research completeness
    if research_completeness_summary:
        for gap in research_completeness_summary.get("incomplete_sections", []):
            missing.append({"field": gap, "source": "research_completeness_agent"})

    # From candidate
    if candidate:
        for field in (candidate.missing_data_json or []):
            if field not in [m["field"] for m in missing]:
                missing.append({"field": field, "source": "screening_candidate"})

    return {
        "type": "missing_information",
        "total_missing_items": len(missing),
        "missing_items": {
            "value": missing,
            "provenance": "sourced_fact",
        },
        "human_review_required": len(missing) > 0,
        "note": (
            "All missing items must be resolved or explicitly acknowledged "
            "before a report can be approved internally."
        ),
    }


def _build_committee_chair_summary(
    committee_chair_summary: dict[str, Any] | None,
) -> dict[str, Any]:
    if committee_chair_summary is None:
        return {
            "type": "committee_chair_summary",
            "available": False,
            "note": {
                "value": "Investment Committee Chair summary not available.",
                "provenance": "missing_data",
            },
            "human_review_required": True,
        }

    status = committee_chair_summary.get("provisional_internal_status", "not_enough_data")
    if status not in ALLOWED_INTERNAL_STATUSES:
        status = "not_enough_data"

    return {
        "type": "committee_chair_summary",
        "available": True,
        "committee_summary": {
            "value": committee_chair_summary.get("committee_summary", ""),
            "provenance": "model_interpretation",
            "source": "investment_committee_chair_phase9",
        },
        "bull_bear_balance": {
            "value": committee_chair_summary.get("bull_bear_balance", "insufficient_data"),
            "provenance": "model_interpretation",
        },
        "provisional_internal_status": {
            "value": status,
            "provenance": "model_interpretation",
            "note": "Research queue label only — not a public investment recommendation.",
        },
        "quality_gate_status": {
            "value": committee_chair_summary.get("quality_gate_status", {}),
            "provenance": "sourced_fact",
        },
        "primary_open_questions": {
            "value": committee_chair_summary.get("primary_open_questions", []),
            "provenance": "model_interpretation",
        },
        "research_next_steps": {
            "value": committee_chair_summary.get("research_next_steps", []),
            "provenance": "model_interpretation",
        },
        "human_review_required": True,
        "warnings": committee_chair_summary.get("warnings", []),
    }


def _build_workflow_status(
    report: Report | None,
    agent_run_id: str | None,
    schema_valid: bool | None,
    human_review_required: bool | None,
) -> dict[str, Any]:
    return {
        "type": "workflow_status",
        "report_id": str(report.id) if report else None,
        "agent_run_id": agent_run_id,
        "review_status": report.review_status if report else "draft",
        "schema_valid": schema_valid,
        "human_review_required": (
            human_review_required if human_review_required is not None else True
        ),
        "final_report_version": FINAL_REPORT_VERSION,
        "generated_at": _utcnow().isoformat(),
        "provenance": "sourced_fact",
    }


def _build_human_review_checklist(
    safety_valid: bool,
    schema_valid: bool,
    has_scorecard: bool,
    has_bull_bear: bool,
    has_risk: bool,
    has_citations: bool,
    missing_count: int,
    is_mock: bool,
) -> list[HumanReviewChecklistItem]:
    items = [
        HumanReviewChecklistItem(
            item="Safety gate passed: no prohibited investment recommendation language detected",
            required=True,
            completed=safety_valid,
            note=None if safety_valid else "BLOCKED: prohibited language found. Revise report.",
        ),
        HumanReviewChecklistItem(
            item="Schema validation passed: report structure conforms to real-asset schema",
            required=False,
            completed=schema_valid,
            note=(
                None
                if schema_valid
                else "Schema invalid — review validation errors and add missing fields."
            ),
        ),
        HumanReviewChecklistItem(
            item="Research attractiveness scorecard is present",
            required=True,
            completed=has_scorecard,
            note=None if has_scorecard else "Run scoring workflow to generate scorecard.",
        ),
        HumanReviewChecklistItem(
            item="Bull/Bear case analysis is present",
            required=True,
            completed=has_bull_bear,
            note=None if has_bull_bear else "Run company analysis workflow (Analysis Council).",
        ),
        HumanReviewChecklistItem(
            item="Risk analysis is present",
            required=True,
            completed=has_risk,
            note=None if has_risk else "Run company analysis workflow (Risk Agent).",
        ),
        HumanReviewChecklistItem(
            item="Citations present in DB",
            required=True,
            completed=has_citations,
            note=None if has_citations else "No citations found. Run analysis workflow.",
        ),
        HumanReviewChecklistItem(
            item=f"Missing information resolved ({missing_count} items)",
            required=missing_count == 0,
            completed=missing_count == 0,
            note=(
                f"{missing_count} missing data items require resolution before approval."
                if missing_count > 0
                else None
            ),
        ),
        HumanReviewChecklistItem(
            item="Data quality: T1/T2 sources present (not mock/T5/T6 only)",
            required=True,
            completed=not is_mock,
            note=(
                "Mock or T5/T6-only data detected. Primary source validation required."
                if is_mock
                else None
            ),
        ),
        HumanReviewChecklistItem(
            item="Admin reviewer has read all sections and confirmed accuracy",
            required=True,
            completed=False,
            note="Manual review step — cannot be auto-completed.",
        ),
        HumanReviewChecklistItem(
            item="Report confirmed as INTERNAL DRAFT ONLY (not public investment advice)",
            required=True,
            completed=False,
            note="Manual confirmation required.",
        ),
    ]
    return items


def _build_source_citation_appendix(
    sources: list[Source],
    citations: list[Citation],
) -> dict[str, Any]:
    source_rows = []
    for s in sources:
        source_rows.append(
            {
                "id": str(s.id),
                "source_type": s.source_type,
                "title": s.title,
                "url": s.url,
                "publisher": s.publisher,
                "credibility_score": (
                    float(s.credibility_score) if s.credibility_score else None
                ),
                "retrieved_at": s.retrieved_at.isoformat() if s.retrieved_at else None,
            }
        )

    citation_rows = []
    for c in citations:
        citation_rows.append(
            {
                "id": str(c.id),
                "source_id": str(c.source_id),
                "claim_text": c.claim_text,
                "field_path": c.field_path,
                "source_tier": c.source_tier,
                "data_quality": c.data_quality,
                "source_quote": c.source_quote,
                "created_at": c.created_at.isoformat() if c.created_at else None,
            }
        )

    return {
        "type": "source_citation_appendix",
        "sources": {
            "value": source_rows,
            "total": len(source_rows),
            "provenance": "sourced_fact",
        },
        "citations": {
            "value": citation_rows,
            "total": len(citation_rows),
            "provenance": "sourced_fact",
        },
        "human_review_required": False,
    }


# ---------------------------------------------------------------------------
# Report content parser — extracts structured data from existing report
# ---------------------------------------------------------------------------


def _extract_from_report_content(report: Report) -> dict[str, Any]:
    """
    Parse an existing report's stored JSON content or structured fields
    to extract the council outputs needed for final report sections.
    """
    content: dict[str, Any] = {}
    if report.content_markdown:
        # Simple heuristic extraction — look for JSON blocks in content
        import json
        import re

        pattern = re.compile(r"```json\s*(.*?)\s*```", re.DOTALL)
        for match in pattern.finditer(report.content_markdown):
            try:
                block = json.loads(match.group(1))
                if isinstance(block, dict):
                    content.update(block)
            except (json.JSONDecodeError, ValueError):
                pass

    return content


# ---------------------------------------------------------------------------
# Core assembly function
# ---------------------------------------------------------------------------


def _assemble_final_report_content(
    company_snapshot: dict[str, Any] | None,
    company_record: dict[str, Any] | None,
    candidate: ScreeningCandidate | None,
    scorecard: Scorecard | None,
    financial_data_summary: dict[str, Any] | None,
    source_quality_summary: dict[str, Any] | None,
    research_completeness_summary: dict[str, Any] | None,
    upgraded_citation_validation: dict[str, Any] | None,
    bull_case_summary: dict[str, Any] | None,
    bear_case_summary: dict[str, Any] | None,
    risk_summary: dict[str, Any] | None,
    valuation_guard_summary: dict[str, Any] | None,
    committee_chair_summary: dict[str, Any] | None,
    fundamentals_data: dict[str, Any] | None,
    fundamentals_available: bool | None,
    source_tier: str | None,
    sources: list[Source],
    citations: list[Citation],
    report: Report | None,
    agent_run_id: str | None,
    schema_valid: bool | None,
    human_review_required: bool | None,
) -> dict[str, Any]:
    """
    Assemble all 19 sections into a structured report dict.
    """
    company_name = None
    ticker = None

    if company_snapshot:
        ci = company_snapshot.get("company_identity", {})
        company_name = ci.get("legal_name")
        ticker = ci.get("ticker")
    elif company_record:
        company_name = company_record.get("name")
        ticker = company_record.get("ticker")
    elif candidate:
        company_name = candidate.name
        ticker = candidate.ticker

    provisional_status = None
    if committee_chair_summary:
        provisional_status = committee_chair_summary.get("provisional_internal_status")
    if scorecard and not provisional_status:
        provisional_status = scorecard.internal_status

    missing_section = _build_missing_information(
        financial_data_summary,
        research_completeness_summary,
        company_snapshot,
        candidate,
    )
    missing_count = missing_section.get("total_missing_items", 0)

    is_mock = True
    if company_snapshot:
        is_mock = company_snapshot.get("is_mock", True)
    elif scorecard:
        source_q = scorecard.source_quality_summary_json or {}
        is_mock = source_q.get("is_mock", True)

    return {
        "admin_disclaimer": _build_admin_disclaimer(),
        "executive_summary": _build_executive_summary(
            company_name,
            ticker,
            scorecard,
            committee_chair_summary,
            provisional_status,
        ),
        "company_identity": _build_company_identity(
            company_snapshot, company_record
        ),
        "discovery_rationale": _build_discovery_rationale(candidate),
        "data_availability_summary": _build_data_availability_summary(
            financial_data_summary, fundamentals_available, source_tier
        ),
        "financial_snapshot": _build_financial_snapshot(
            company_snapshot, fundamentals_data
        ),
        "internal_scorecard": _build_internal_scorecard(scorecard),
        "valuation_readiness": _build_valuation_readiness(
            valuation_guard_summary, scorecard
        ),
        "bull_case": _build_bull_case(bull_case_summary),
        "bear_case": _build_bear_case(bear_case_summary),
        "risk_analysis": _build_risk_analysis(risk_summary),
        "source_quality_review": _build_source_quality_review(
            source_quality_summary, sources
        ),
        "citation_validation_review": _build_citation_validation_review(
            upgraded_citation_validation, citations
        ),
        "research_completeness_review": _build_research_completeness_review(
            research_completeness_summary
        ),
        "missing_information": missing_section,
        "committee_chair_summary": _build_committee_chair_summary(
            committee_chair_summary
        ),
        "workflow_status": _build_workflow_status(
            report, agent_run_id, schema_valid, human_review_required
        ),
        "human_review_checklist": [
            item.model_dump()
            for item in _build_human_review_checklist(
                safety_valid=True,  # placeholder — updated after safety gate
                schema_valid=schema_valid or False,
                has_scorecard=scorecard is not None,
                has_bull_bear=bull_case_summary is not None
                and bear_case_summary is not None,
                has_risk=risk_summary is not None,
                has_citations=len(citations) > 0,
                missing_count=missing_count,
                is_mock=is_mock,
            )
        ],
        "source_citation_appendix": _build_source_citation_appendix(
            sources, citations
        ),
    }


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------


async def _load_scorecard_by_id(
    db: AsyncSession, scorecard_id: uuid.UUID
) -> Scorecard | None:
    result = await db.execute(
        select(Scorecard).where(Scorecard.id == scorecard_id)
    )
    return result.scalar_one_or_none()


async def _load_scorecard_for_candidate(
    db: AsyncSession, candidate_id: uuid.UUID
) -> Scorecard | None:
    result = await db.execute(
        select(Scorecard)
        .where(Scorecard.screening_candidate_id == candidate_id)
        .order_by(Scorecard.created_at.desc())
        .limit(1)
    )
    return result.scalar_one_or_none()


async def _load_scorecard_for_company(
    db: AsyncSession, company_id: uuid.UUID
) -> Scorecard | None:
    result = await db.execute(
        select(Scorecard)
        .where(Scorecard.company_id == company_id)
        .order_by(Scorecard.created_at.desc())
        .limit(1)
    )
    return result.scalar_one_or_none()


async def _load_scorecard_for_report(
    db: AsyncSession, report_id: uuid.UUID
) -> Scorecard | None:
    result = await db.execute(
        select(Scorecard)
        .where(Scorecard.report_id == report_id)
        .order_by(Scorecard.created_at.desc())
        .limit(1)
    )
    return result.scalar_one_or_none()


async def _load_candidate_by_id(
    db: AsyncSession, candidate_id: uuid.UUID
) -> ScreeningCandidate | None:
    result = await db.execute(
        select(ScreeningCandidate).where(ScreeningCandidate.id == candidate_id)
    )
    return result.scalar_one_or_none()


async def _load_candidate_for_company(
    db: AsyncSession, company_id: uuid.UUID
) -> ScreeningCandidate | None:
    result = await db.execute(
        select(ScreeningCandidate)
        .where(ScreeningCandidate.company_id == company_id)
        .order_by(ScreeningCandidate.created_at.desc())
        .limit(1)
    )
    return result.scalar_one_or_none()


async def _load_report_by_id(
    db: AsyncSession, report_id: uuid.UUID
) -> Report | None:
    result = await db.execute(
        select(Report).where(Report.id == report_id)
    )
    return result.scalar_one_or_none()


async def _load_latest_report_for_run(
    db: AsyncSession, agent_run_id: str
) -> Report | None:
    result = await db.execute(
        select(Report)
        .where(Report.created_by_agent_run_id == uuid.UUID(agent_run_id))
        .order_by(Report.created_at.desc())
        .limit(1)
    )
    return result.scalar_one_or_none()


async def _load_citations_for_report(
    db: AsyncSession, report_id: uuid.UUID
) -> list[Citation]:
    result = await db.execute(
        select(Citation).where(Citation.report_id == report_id)
    )
    return list(result.scalars().all())


async def _load_sources_for_citations(
    db: AsyncSession, citations: list[Citation]
) -> list[Source]:
    if not citations:
        return []
    source_ids = list({c.source_id for c in citations})
    result = await db.execute(
        select(Source).where(Source.id.in_(source_ids))
    )
    return list(result.scalars().all())


def _extract_workflow_state_from_report(
    report: Report,
) -> dict[str, Any]:
    """
    Try to extract workflow state fields from an existing report's content.
    Falls back to empty dicts when not found.
    """
    parsed = _extract_from_report_content(report)
    return {
        "company_snapshot": parsed.get("company_snapshot"),
        "financial_data_summary": parsed.get("financial_data_summary"),
        "source_quality_summary": parsed.get("source_quality_summary"),
        "research_completeness_summary": parsed.get("research_completeness_summary"),
        "upgraded_citation_validation": parsed.get("upgraded_citation_validation"),
        "bull_case_summary": parsed.get("bull_case_summary"),
        "bear_case_summary": parsed.get("bear_case_summary"),
        "risk_summary": parsed.get("risk_summary"),
        "valuation_guard_summary": parsed.get("valuation_guard_summary"),
        "committee_chair_summary": parsed.get("committee_chair_summary"),
        "fundamentals_data": parsed.get("fundamentals_data"),
        "fundamentals_available": parsed.get("fundamentals_available"),
        "schema_validation_result": parsed.get("schema_validation_result"),
        "source_tier": (
            parsed.get("company_snapshot", {}).get("source_tier")
            if parsed.get("company_snapshot")
            else None
        ),
    }


# ---------------------------------------------------------------------------
# Core save logic
# ---------------------------------------------------------------------------


async def _save_final_report_draft(
    db: AsyncSession,
    report_content: dict[str, Any],
    safety_result: SafetyValidationResult,
    schema_validation: dict[str, Any],
    source_summary: dict[str, Any],
    scorecard_id: uuid.UUID | None,
    company_name: str | None,
    ticker: str | None,
    source_report_id: uuid.UUID | None,
) -> Report:
    """
    Save the assembled final report as a new draft report record.
    """
    import json

    title_prefix = f"Final Report Draft — {company_name or 'Unknown'}"
    if ticker:
        title_prefix = f"Final Report Draft — {ticker} — {company_name or 'Unknown'}"

    slug = (
        f"final-report-{ticker or 'unknown'}-{uuid.uuid4().hex[:8]}"
        .lower()
        .replace(" ", "-")
    )

    # Build markdown summary for content_markdown
    content_lines = [
        "# INTERNAL ADMIN DRAFT — FINAL REPORT",
        "",
        "NOT INVESTMENT ADVICE. NOT A PUBLIC TRADING RECOMMENDATION. Human review required.",
        "",
        "---",
        "",
        "## Report Sections (Structured JSON — see safety_validation_json"
        " and schema_validation_json for validation status)",
        "",
        "```json",
        json.dumps(report_content, indent=2, default=str),
        "```",
    ]
    content_markdown = "\n".join(content_lines)

    schema_valid = schema_validation.get("is_valid", False)

    report = Report(
        id=uuid.uuid4(),
        title=title_prefix,
        slug=slug,
        report_type="company_deep_dive",
        status="draft",
        summary=(
            f"Phase 16 final report draft for {company_name or 'Unknown'}. "
            f"Safety: {'PASSED' if safety_result.passed else 'FAILED'}. "
            f"Schema: {'valid' if schema_valid else 'invalid'}. "
            f"Human review required."
        ),
        content_markdown=content_markdown,
        review_status="draft",
        human_review_required=True,
        final_report_version=FINAL_REPORT_VERSION,
        safety_validation_json=safety_result.model_dump(),
        schema_validation_json=schema_validation,
        source_summary_json=source_summary,
        scorecard_id=scorecard_id,
    )

    db.add(report)
    await db.flush()
    await db.refresh(report)
    return report


# ---------------------------------------------------------------------------
# FinalReportGeneratorService
# ---------------------------------------------------------------------------


class FinalReportGeneratorService:
    """
    Generates structured internal final report drafts.

    Entry points:
      generate_from_scorecard(db, scorecard_id)
      generate_from_candidate(db, candidate_id)
      generate_from_company(db, company_id)
      generate_from_report(db, report_id)
      validate_final_report(db, report_id)
      regenerate_report_section(db, report_id, section_name)

    All outputs are admin-only drafts with human_review_required=True.
    No BUY/SELL/HOLD/WATCH recommendations are ever produced.
    No price targets, fair values, or upside percentages are ever produced.
    """

    async def generate_from_scorecard(
        self, db: AsyncSession, scorecard_id: uuid.UUID
    ) -> FinalReportResponse:
        """Generate a final report draft from a scorecard record."""
        scorecard = await _load_scorecard_by_id(db, scorecard_id)
        if scorecard is None:
            raise ValueError(f"Scorecard {scorecard_id} not found.")

        candidate = None
        source_report = None
        company_record = None

        if scorecard.screening_candidate_id:
            candidate = await _load_candidate_by_id(
                db, scorecard.screening_candidate_id
            )

        if scorecard.report_id:
            source_report = await _load_report_by_id(db, scorecard.report_id)

        # Extract workflow state from the linked report if available
        state: dict[str, Any] = {}
        if source_report:
            state = _extract_workflow_state_from_report(source_report)

        citations: list[Citation] = []
        sources: list[Source] = []
        if source_report:
            citations = await _load_citations_for_report(db, source_report.id)
            sources = await _load_sources_for_citations(db, citations)

        return await self._generate_and_save(
            db=db,
            scorecard=scorecard,
            candidate=candidate,
            source_report=source_report,
            company_record=company_record,
            citations=citations,
            sources=sources,
            state=state,
        )

    async def generate_from_candidate(
        self, db: AsyncSession, candidate_id: uuid.UUID
    ) -> FinalReportResponse:
        """Generate a final report draft from a screening candidate."""
        candidate = await _load_candidate_by_id(db, candidate_id)
        if candidate is None:
            raise ValueError(f"Screening candidate {candidate_id} not found.")

        scorecard = await _load_scorecard_for_candidate(db, candidate_id)

        source_report = None
        citations: list[Citation] = []
        sources: list[Source] = []
        state: dict[str, Any] = {}

        # Look for a report linked to the candidate's company
        if candidate.company_id:
            # Find most recent report linked to the company via agent_runs
            from app.models.agent_run import AgentRun

            run_result = await db.execute(
                select(AgentRun)
                .where(AgentRun.status == "completed")
                .order_by(AgentRun.started_at.desc())
                .limit(1)
            )
            latest_run = run_result.scalar_one_or_none()
            if latest_run:
                source_report = await _load_latest_report_for_run(
                    db, str(latest_run.id)
                )

        if source_report:
            state = _extract_workflow_state_from_report(source_report)
            citations = await _load_citations_for_report(db, source_report.id)
            sources = await _load_sources_for_citations(db, citations)

        return await self._generate_and_save(
            db=db,
            scorecard=scorecard,
            candidate=candidate,
            source_report=source_report,
            company_record=None,
            citations=citations,
            sources=sources,
            state=state,
        )

    async def generate_from_company(
        self, db: AsyncSession, company_id: uuid.UUID
    ) -> FinalReportResponse:
        """Generate a final report draft for a company."""
        from app.models.company import Company

        company_result = await db.execute(
            select(Company).where(Company.id == company_id)
        )
        company = company_result.scalar_one_or_none()
        if company is None:
            raise ValueError(f"Company {company_id} not found.")

        company_record = {
            "id": str(company.id),
            "name": company.name,
            "ticker": company.ticker,
            "exchange": company.exchange,
            "country": company.country,
            "sector": company.sector,
            "industry": company.industry,
        }

        scorecard = await _load_scorecard_for_company(db, company_id)
        candidate = await _load_candidate_for_company(db, company_id)

        # Find most recent completed report via agent_runs
        from app.models.agent_run import AgentRun

        report_result = await db.execute(
            select(Report)
            .join(AgentRun, Report.created_by_agent_run_id == AgentRun.id)
            .where(AgentRun.status == "completed")
            .order_by(Report.created_at.desc())
            .limit(1)
        )
        source_report = report_result.scalar_one_or_none()

        state: dict[str, Any] = {}
        citations: list[Citation] = []
        sources: list[Source] = []

        if source_report:
            state = _extract_workflow_state_from_report(source_report)
            citations = await _load_citations_for_report(db, source_report.id)
            sources = await _load_sources_for_citations(db, citations)

        return await self._generate_and_save(
            db=db,
            scorecard=scorecard,
            candidate=candidate,
            source_report=source_report,
            company_record=company_record,
            citations=citations,
            sources=sources,
            state=state,
        )

    async def generate_from_report(
        self, db: AsyncSession, report_id: uuid.UUID
    ) -> FinalReportResponse:
        """Generate a final report draft from an existing report."""
        source_report = await _load_report_by_id(db, report_id)
        if source_report is None:
            raise ValueError(f"Report {report_id} not found.")

        state = _extract_workflow_state_from_report(source_report)
        scorecard = await _load_scorecard_for_report(db, report_id)
        if not scorecard and source_report.scorecard_id:
            scorecard = await _load_scorecard_by_id(db, source_report.scorecard_id)

        citations = await _load_citations_for_report(db, report_id)
        sources = await _load_sources_for_citations(db, citations)

        return await self._generate_and_save(
            db=db,
            scorecard=scorecard,
            candidate=None,
            source_report=source_report,
            company_record=None,
            citations=citations,
            sources=sources,
            state=state,
        )

    async def validate_final_report(
        self, db: AsyncSession, report_id: uuid.UUID
    ) -> FinalReportValidateResponse:
        """Re-validate an existing final report (safety + schema)."""
        report = await _load_report_by_id(db, report_id)
        if report is None:
            raise ValueError(f"Report {report_id} not found.")

        import json

        # Parse the content for safety + schema validation
        report_content: dict[str, Any] = {}
        if report.content_markdown:
            import re

            pattern = re.compile(r"```json\s*(.*?)\s*```", re.DOTALL)
            for match in pattern.finditer(report.content_markdown):
                try:
                    block = json.loads(match.group(1))
                    if isinstance(block, dict):
                        report_content = block
                        break
                except (json.JSONDecodeError, ValueError):
                    pass

        safety_result = run_safety_gate(report_content)

        # Schema validation against real-asset schema
        schema_result = validate_real_asset_report(report_content)
        schema_valid = schema_result.is_valid

        sections_present = [k for k in report_content if k in _REQUIRED_SECTIONS]
        missing_sections = [s for s in _REQUIRED_SECTIONS if s not in report_content]

        validation_warnings: list[str] = list(schema_result.warnings or [])
        if not safety_result.passed:
            validation_warnings.extend(safety_result.warnings)

        # Update the report's validation fields
        report.safety_validation_json = safety_result.model_dump()
        report.schema_validation_json = {
            "is_valid": schema_valid,
            "errors": list(schema_result.errors or []),
            "warnings": list(schema_result.warnings or []),
        }
        await db.flush()

        return FinalReportValidateResponse(
            report_id=report.id,
            schema_valid=schema_valid,
            safety_valid=safety_result.passed,
            human_review_required=True,
            safety_validation=safety_result,
            schema_validation_errors=list(schema_result.errors or []),
            schema_validation_warnings=list(schema_result.warnings or []),
            validation_warnings=validation_warnings,
            sections_present=sections_present,
            missing_sections=missing_sections,
        )

    async def regenerate_report_section(
        self, db: AsyncSession, report_id: uuid.UUID, section_name: str
    ) -> RegenerateSectionResponse:
        """Regenerate a single section of an existing final report."""
        if section_name not in _REQUIRED_SECTIONS:
            raise ValueError(
                f"Unknown section '{section_name}'. "
                f"Valid sections: {sorted(_REQUIRED_SECTIONS)}"
            )

        report = await _load_report_by_id(db, report_id)
        if report is None:
            raise ValueError(f"Report {report_id} not found.")

        # For deterministic regeneration, rebuild the section from workflow state
        state = _extract_workflow_state_from_report(report)
        scorecard: Scorecard | None = None
        if report.scorecard_id:
            scorecard = await _load_scorecard_by_id(db, report.scorecard_id)

        # Build only the requested section
        section_content: dict[str, Any] = {}
        match section_name:
            case "admin_disclaimer":
                section_content = _build_admin_disclaimer()
            case "executive_summary":
                section_content = _build_executive_summary(
                    None, None, scorecard,
                    state.get("committee_chair_summary"),
                    state.get("committee_chair_summary", {}).get(
                        "provisional_internal_status"
                    ) if state.get("committee_chair_summary") else None,
                )
            case "internal_scorecard":
                section_content = _build_internal_scorecard(scorecard)
            case "valuation_readiness":
                section_content = _build_valuation_readiness(
                    state.get("valuation_guard_summary"), scorecard
                )
            case "bull_case":
                section_content = _build_bull_case(state.get("bull_case_summary"))
            case "bear_case":
                section_content = _build_bear_case(state.get("bear_case_summary"))
            case "risk_analysis":
                section_content = _build_risk_analysis(state.get("risk_summary"))
            case "committee_chair_summary":
                section_content = _build_committee_chair_summary(
                    state.get("committee_chair_summary")
                )
            case "research_completeness_review":
                section_content = _build_research_completeness_review(
                    state.get("research_completeness_summary")
                )
            case _:
                section_content = {
                    "note": f"Section '{section_name}' requires full report regeneration.",
                    "provenance": "missing_data",
                }

        safety_result = run_safety_gate({section_name: section_content})

        warnings: list[str] = list(safety_result.warnings)
        if not safety_result.passed:
            warnings.append(
                f"Section '{section_name}' contains forbidden terms. "
                "Cannot update report section."
            )

        return RegenerateSectionResponse(
            report_id=report.id,
            section_name=section_name,
            regenerated=safety_result.passed,
            safety_valid=safety_result.passed,
            warnings=warnings,
        )

    # ── Core private assembly ─────────────────────────────────────────────────

    async def _generate_and_save(
        self,
        db: AsyncSession,
        scorecard: Scorecard | None,
        candidate: ScreeningCandidate | None,
        source_report: Report | None,
        company_record: dict[str, Any] | None,
        citations: list[Citation],
        sources: list[Source],
        state: dict[str, Any],
    ) -> FinalReportResponse:
        company_snapshot = state.get("company_snapshot")
        financial_data_summary = state.get("financial_data_summary")
        source_quality_summary = state.get("source_quality_summary")
        research_completeness_summary = state.get("research_completeness_summary")
        upgraded_citation_validation = state.get("upgraded_citation_validation")
        bull_case_summary = state.get("bull_case_summary")
        bear_case_summary = state.get("bear_case_summary")
        risk_summary = state.get("risk_summary")
        valuation_guard_summary = state.get("valuation_guard_summary")
        committee_chair_summary = state.get("committee_chair_summary")
        fundamentals_data = state.get("fundamentals_data")
        fundamentals_available = state.get("fundamentals_available")
        schema_validation_result = state.get("schema_validation_result")
        source_tier = state.get("source_tier") or (
            company_snapshot.get("source_tier") if company_snapshot else None
        )

        schema_valid = (
            schema_validation_result.get("is_valid", False)
            if schema_validation_result
            else False
        )
        human_review_required = True

        report_content = _assemble_final_report_content(
            company_snapshot=company_snapshot,
            company_record=company_record,
            candidate=candidate,
            scorecard=scorecard,
            financial_data_summary=financial_data_summary,
            source_quality_summary=source_quality_summary,
            research_completeness_summary=research_completeness_summary,
            upgraded_citation_validation=upgraded_citation_validation,
            bull_case_summary=bull_case_summary,
            bear_case_summary=bear_case_summary,
            risk_summary=risk_summary,
            valuation_guard_summary=valuation_guard_summary,
            committee_chair_summary=committee_chair_summary,
            fundamentals_data=fundamentals_data,
            fundamentals_available=fundamentals_available,
            source_tier=source_tier,
            sources=sources,
            citations=citations,
            report=source_report,
            agent_run_id=str(source_report.created_by_agent_run_id)
            if source_report and source_report.created_by_agent_run_id
            else None,
            schema_valid=schema_valid,
            human_review_required=human_review_required,
        )

        # Run safety gate
        safety_result = run_safety_gate(report_content)

        # Update checklist with actual safety result
        checklist = report_content.get("human_review_checklist", [])
        if checklist and isinstance(checklist[0], dict):
            checklist[0]["completed"] = safety_result.passed
            if not safety_result.passed:
                checklist[0]["note"] = (
                    "BLOCKED: forbidden terms found. Revise report."
                )

        # Schema validation
        schema_check = validate_real_asset_report(report_content)
        schema_validation_for_save = {
            "is_valid": schema_check.is_valid,
            "errors": list(schema_check.errors or []),
            "warnings": list(schema_check.warnings or []),
        }

        # Source summary
        source_summary_for_save = {
            "total_sources": len(sources),
            "total_citations": len(citations),
            "source_types": list({s.source_type for s in sources}),
        }

        # Derive company_name + ticker for title
        company_name: str | None = None
        ticker: str | None = None
        if company_snapshot:
            ci = company_snapshot.get("company_identity", {})
            company_name = ci.get("legal_name")
            ticker = ci.get("ticker")
        elif company_record:
            company_name = company_record.get("name")
            ticker = company_record.get("ticker")
        elif candidate:
            company_name = candidate.name
            ticker = candidate.ticker

        saved_report = await _save_final_report_draft(
            db=db,
            report_content=report_content,
            safety_result=safety_result,
            schema_validation=schema_validation_for_save,
            source_summary=source_summary_for_save,
            scorecard_id=scorecard.id if scorecard else None,
            company_name=company_name,
            ticker=ticker,
            source_report_id=source_report.id if source_report else None,
        )

        sections_generated = list(report_content.keys())
        missing_sections = [s for s in _REQUIRED_SECTIONS if s not in report_content]

        # Build human review checklist items for response
        missing_count_val = report_content.get("missing_information", {}).get(
            "total_missing_items", 0
        )
        is_mock_val = True
        if company_snapshot:
            is_mock_val = company_snapshot.get("is_mock", True)

        checklist_items = _build_human_review_checklist(
            safety_valid=safety_result.passed,
            schema_valid=schema_check.is_valid,
            has_scorecard=scorecard is not None,
            has_bull_bear=bull_case_summary is not None
            and bear_case_summary is not None,
            has_risk=risk_summary is not None,
            has_citations=len(citations) > 0,
            missing_count=missing_count_val,
            is_mock=is_mock_val,
        )

        provisional_status = None
        if committee_chair_summary:
            provisional_status = committee_chair_summary.get(
                "provisional_internal_status"
            )
        if not provisional_status and scorecard:
            provisional_status = scorecard.internal_status
        if not provisional_status or provisional_status not in ALLOWED_INTERNAL_STATUSES:
            provisional_status = "not_enough_data"

        validation_warnings: list[str] = list(schema_check.warnings or [])
        if not safety_result.passed:
            validation_warnings.extend(safety_result.warnings)

        return FinalReportResponse(
            report_id=saved_report.id,
            status="draft",
            review_status="draft",
            schema_valid=schema_check.is_valid,
            safety_valid=safety_result.passed,
            human_review_required=True,
            internal_status=provisional_status,
            sections_generated=sections_generated,
            missing_sections=missing_sections,
            safety_validation=safety_result,
            schema_validation_errors=list(schema_check.errors or []),
            schema_validation_warnings=list(schema_check.warnings or []),
            validation_warnings=validation_warnings,
            scorecard_id=scorecard.id if scorecard else None,
            source_count=len(sources),
            citation_count=len(citations),
            human_review_checklist=checklist_items,
        )
