import Link from "next/link";
import { fetchReports } from "@/lib/api";
import type { Report } from "@/types/api";
import GlassCard from "@/components/ui/GlassCard";
import SafetyBanner from "@/components/ui/SafetyBanner";
import StatusPill, { type PillColor } from "@/components/ui/StatusPill";

export const dynamic = "force-dynamic";

function reviewStatusColor(status: string): PillColor {
  if (status === "approved_internal") return "green";
  if (status === "rejected_internal") return "red";
  if (status === "under_review") return "blue";
  if (status === "needs_revision") return "purple";
  if (status === "draft") return "amber";
  return "gray";
}

function schemaValidLabel(report: Report): string {
  const value = report.schema_validation_json?.is_valid;
  if (typeof value === "boolean") return value ? "Schema OK" : "Schema Issues";
  return "Schema n/a";
}

const REVIEW_STATUS_LABELS: Record<string, string> = {
  draft: "Draft",
  under_review: "Under Review",
  approved_internal: "Approved (Internal)",
  rejected_internal: "Rejected",
  needs_revision: "Needs Revision",
  archived: "Archived",
};

async function getReports() {
  try {
    return await fetchReports(50, 0);
  } catch {
    return null;
  }
}

export default async function ReportsPage() {
  const data = await getReports();

  return (
    <div className="ib-fade-up space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white">
            Draft Reports
          </h1>
          <p className="mt-1 text-sm text-slate-400">
            All draft reports generated by the analysis workflow. Internal admin
            view only.
          </p>
        </div>
        <Link
          href="/admin/analysis"
          className="rounded-lg bg-gradient-to-r from-sky-500 to-blue-600 px-3.5 py-1.5 text-sm font-semibold text-white shadow-lg shadow-sky-500/20 transition-all hover:-translate-y-0.5 hover:shadow-sky-500/30"
        >
          + Run Analysis
        </Link>
      </div>

      {/* Disclaimer */}
      <SafetyBanner variant="danger">
        <p>
          <strong>Admin only.</strong> These are internal draft reports — not
          investment advice, not public recommendations. Every report must be
          reviewed and approved by a human before publication.
        </p>
      </SafetyBanner>

      {data === null && (
        <SafetyBanner variant="warning">
          <p>Could not fetch reports — is the backend running?</p>
        </SafetyBanner>
      )}

      {data && data.total === 0 && (
        <GlassCard className="p-8 text-center text-slate-400">
          <p className="text-sm">No draft reports yet.</p>
          <p className="mt-1 text-xs text-slate-500">
            Run an analysis to generate the first report.
          </p>
          <Link
            href="/admin/analysis"
            className="mt-3 inline-block text-sm text-sky-400 hover:text-sky-300 hover:underline"
          >
            → Run Analysis
          </Link>
        </GlassCard>
      )}

      {data && data.total > 0 && (
        <GlassCard className="overflow-hidden">
          <div className="flex items-center justify-between border-b border-white/10 px-5 py-3">
            <p className="text-sm text-slate-400">
              {data.total} report{data.total !== 1 ? "s" : ""}
            </p>
            <StatusPill label="Admin Draft Only" color="red" />
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-white/10 text-xs uppercase tracking-wide text-slate-500">
                  <th className="px-5 py-2.5 text-left font-medium">Title</th>
                  <th className="px-3 py-2.5 text-left font-medium">Type</th>
                  <th className="px-3 py-2.5 text-left font-medium">
                    Review Status
                  </th>
                  <th className="px-3 py-2.5 text-left font-medium">
                    Final Report
                  </th>
                  <th className="px-3 py-2.5 text-left font-medium">Created</th>
                  <th className="px-3 py-2.5 text-left font-medium"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {data.items.map((r: Report) => (
                  <tr key={r.id} className="transition-colors hover:bg-white/5">
                    <td className="max-w-xs px-5 py-3">
                      <Link
                        href={`/admin/reports/${r.id}`}
                        className="line-clamp-1 text-sky-300 hover:text-sky-200 hover:underline"
                      >
                        {r.title}
                      </Link>
                      {r.summary && (
                        <p className="mt-0.5 line-clamp-1 text-xs text-slate-500">
                          {r.summary}
                        </p>
                      )}
                    </td>
                    <td className="whitespace-nowrap px-3 py-3 text-xs text-slate-400">
                      {r.report_type}
                    </td>
                    <td className="whitespace-nowrap px-3 py-3">
                      <StatusPill
                        label={
                          REVIEW_STATUS_LABELS[r.review_status] ??
                          r.review_status ??
                          "draft"
                        }
                        color={reviewStatusColor(r.review_status ?? "draft")}
                      />
                    </td>
                    <td className="px-3 py-3 text-xs text-slate-400">
                      <div>
                        {r.final_report_version ?? "No final report yet"}
                      </div>
                      <div className="text-slate-500">
                        {schemaValidLabel(r)}
                      </div>
                    </td>
                    <td className="whitespace-nowrap px-3 py-3 text-xs text-slate-500">
                      {new Date(r.created_at).toLocaleDateString()}
                    </td>
                    <td className="whitespace-nowrap px-3 py-3">
                      <Link
                        href={`/admin/reports/${r.id}`}
                        className="text-xs text-sky-400 hover:text-sky-300 hover:underline"
                      >
                        View →
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </GlassCard>
      )}
    </div>
  );
}
