import Link from "next/link";
import { fetchReports } from "@/lib/api";
import type { Report } from "@/types/api";

function Badge({
  label,
  color,
}: {
  label: string;
  color: "gray" | "amber" | "green" | "red" | "blue" | "purple";
}) {
  const styles: Record<string, string> = {
    gray: "bg-gray-100 text-gray-700",
    amber: "bg-amber-100 text-amber-800",
    green: "bg-green-100 text-green-800",
    red: "bg-red-100 text-red-800",
    blue: "bg-blue-100 text-blue-800",
    purple: "bg-purple-100 text-purple-800",
  };
  return (
    <span className={`inline-block px-2 py-0.5 rounded text-xs font-semibold ${styles[color]}`}>
      {label}
    </span>
  );
}

function reviewStatusColor(
  status: string,
): "gray" | "amber" | "green" | "red" | "blue" | "purple" {
  if (status === "approved_internal") return "green";
  if (status === "rejected_internal") return "red";
  if (status === "under_review") return "blue";
  if (status === "needs_revision") return "purple";
  if (status === "draft") return "amber";
  return "gray";
}

const REVIEW_STATUS_LABELS: Record<string, string> = {
  draft: "Draft",
  under_review: "Under Review",
  approved_internal: "Approved (Internal)",
  rejected_internal: "Rejected",
  needs_revision: "Needs Revision",
  archived: "Archived",
};

async function getReports() {
  try {
    return await fetchReports(50, 0);
  } catch {
    return null;
  }
}

export default async function ReportsPage() {
  const data = await getReports();

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-gray-900">Draft Reports</h1>
          <p className="text-sm text-gray-500 mt-1">
            All draft reports generated by the analysis workflow. Internal admin
            view only.
          </p>
        </div>
        <Link
          href="/admin/analysis"
          className="bg-blue-700 text-white rounded-md px-3 py-1.5 text-sm font-semibold hover:bg-blue-800 transition-colors"
        >
          + Run Analysis
        </Link>
      </div>

      {/* Disclaimer */}
      <div className="rounded-lg border border-red-200 bg-red-50 p-3">
        <p className="text-xs text-red-700">
          <strong>Admin only.</strong> These are internal draft reports — not
          investment advice, not public recommendations. Every report must be
          reviewed and approved by a human before publication.
        </p>
      </div>

      {data === null && (
        <div className="rounded-lg border border-amber-200 bg-amber-50 p-4">
          <p className="text-sm text-amber-800">
            Could not fetch reports — is the backend running?
          </p>
        </div>
      )}

      {data && data.total === 0 && (
        <div className="rounded-lg border border-gray-200 bg-white p-8 text-center text-gray-500">
          <p className="text-sm">No draft reports yet.</p>
          <p className="text-xs mt-1">
            Run an analysis to generate the first report.
          </p>
          <Link
            href="/admin/analysis"
            className="inline-block mt-3 text-blue-600 text-sm hover:underline"
          >
            → Run Analysis
          </Link>
        </div>
      )}

      {data && data.total > 0 && (
        <div className="rounded-lg border border-gray-200 bg-white shadow-sm overflow-hidden">
          <div className="px-5 py-3 border-b border-gray-100 flex items-center justify-between">
            <p className="text-sm text-gray-500">
              {data.total} report{data.total !== 1 ? "s" : ""}
            </p>
            <Badge label="Admin Draft Only" color="red" />
          </div>
          <table className="w-full text-sm">
            <thead>
              <tr className="text-xs text-gray-500 uppercase tracking-wide border-b border-gray-100">
                <th className="px-5 py-2 text-left font-medium">Title</th>
                <th className="px-3 py-2 text-left font-medium">Type</th>
                <th className="px-3 py-2 text-left font-medium">Review Status</th>
                <th className="px-3 py-2 text-left font-medium">Created</th>
                <th className="px-3 py-2 text-left font-medium"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {data.items.map((r: Report) => (
                <tr key={r.id} className="hover:bg-gray-50">
                  <td className="px-5 py-3 max-w-xs">
                    <Link
                      href={`/admin/reports/${r.id}`}
                      className="text-blue-700 hover:underline line-clamp-1"
                    >
                      {r.title}
                    </Link>
                    {r.summary && (
                      <p className="text-xs text-gray-400 mt-0.5 line-clamp-1">
                        {r.summary}
                      </p>
                    )}
                  </td>
                  <td className="px-3 py-3 text-xs text-gray-500 whitespace-nowrap">
                    {r.report_type}
                  </td>
                  <td className="px-3 py-3 whitespace-nowrap">
                    <Badge
                      label={REVIEW_STATUS_LABELS[r.review_status] ?? r.review_status ?? "draft"}
                      color={reviewStatusColor(r.review_status ?? "draft")}
                    />
                  </td>
                  <td className="px-3 py-3 text-xs text-gray-400 whitespace-nowrap">
                    {new Date(r.created_at).toLocaleDateString()}
                  </td>
                  <td className="px-3 py-3 whitespace-nowrap">
                    <Link
                      href={`/admin/reports/${r.id}`}
                      className="text-xs text-blue-600 hover:underline"
                    >
                      View →
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
